version: '3.7'

services:
  php-fpm:
    build: .
    container_name: web
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default:/etc/nginx/sites-available/default
    restart: always
    depends_on:
      - 'mysql'
  mysql:
    image: mysql:5.7
    container_name: mysql
    command:
      [
        # origin default is caching_sha2_password
        --default-authentication-plugin=mysql_native_password,
      ]
    volumes:
      - ./mysql/setup_db.sql:/docker-entrypoint-initdb.d/init.sql:ro
      # - mysql-data:/var/lib/mysql:rw
      # - mysql-config:/etc/mysql:rw
    environment: 
      MYSQL_ROOT_PASSWORD: nctfu
    restart: always

volumes: 
  mysql-config:
    name: db-config
  mysql-data:
    name: db-data